[package]
name = "crypt_xor"
version = "0.1.0"
authors = ["Phil <PhilboBaggins@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
exitcode = "1.1.2"
indicatif = "0.13.0"
rand = "0.7.2"
